spring:
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ez_lorry_db_dev?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    jpa:
      hibernate:
        use-new-id-generator-mappings: false 
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
        id:
          new_generator_mappings: false
#  zipkin:
#    enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
  service-url:
    defaultzone: http://localhost:8761/eureka/

sapp: 
  security:
    jwt: 
      keystore-location: keys/keystore.jks
      keystore-password: X0LDM7JLwfyt
      key-alias: jwtsigning
      private-key-passphrase: X0LDM7JLwfyt
     
